stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py  # Corrected path
    deps:
    - data/interim
    - src/features/feature_engineering.py  # Corrected path
    params:
    - feature_engineering.test_size
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py  # Corrected path
    deps:
    - data/processed
    - src/model/model_building.py  # Corrected path
    params:
    - model_building.max_depth
    - model_building.max_leaf_nodes
    outs:
    - model.pkl

  model_evalution:
    cmd: python src/model/model_evalution.py  # Corrected path
    deps:
    - model.pkl
    - src/model/model_evalution.py  # Corrected path
    metrics:
    - metrics.json
