stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    params:
    - feature_engineering.test_size
    outs:
    - data/data_split
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/data_split
    - src/model_building.py
    params:
    - model_building.max_depth
    - model_building.max_leaf_nodes
    outs:
    - model.pkl

  model_evalution:
    cmd: python src/model_evalution.py
    deps:
    - model.pkl
    - src/model_evalution.py
    metrics:
    - metrics.json
